config/routes.rb
Rails.application.routes.draw do
  resources :posts
  devise_for :users
  # get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"

  post "toggle_like", to: "likes#toggle_like", as: :toggle_like

  resources :comments, only: [:create, :destroy]

  resources :users, only: [:show, :index]

  post "follow", to: "follows#follow", as: :follow
  delete "unfollow", to: "follows#unfollow", as: :unfollow
  delete "cancel_request", to: "follows#cancel_request", as: :cancel_request

  post "accept_follow", to: "follows#accept_follow", as: :accept_follow
  delete "decline_follow", to: "follows#decline_follow", as: :decline_follow

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many_attached :images

  validates :images, presence: true, blob: { content_type: :image }

  has_many :likes, dependent: :destroy
  has_many :likers, through: :likes, source: :user

  has_many :comments, dependent: :destroy
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]

  # GET /posts or /posts.json
  def index
    redirect_to root_path
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = current_user.posts.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { redirect_to root_path, status: :unprocessable_entity, alert: @post.errors.full_messages }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    return if current_user != @post.user

    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:caption, :longitude, :latitude, :user_id, :allow_comments, :show_likes_count, images: [])
  end
end

app/views/posts/_form.html.erb
<!-- Modal -->
<div class="modal fade modal-lg" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-fluid">
    <%= form_with(model: post) do |form| %>
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="staticBackdropLabel">Create new post</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body d-flex">

          <div class="border-end border-secondary mx-2" style="width:60%">
            <%= form.file_field :images, multiple: true, id: "post-images", required: true %>
          </div>

          <div style="width:40%">
            <% if post.errors.any? %>
              <div style="color: red">
                <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>
                <ul>
                  <% post.errors.each do |error| %>
                    <li><%= error.full_message %></li>
                  <% end %>
                </ul>
              </div>
            <% end %>

            <div class="my-2">
              <% if current_user.profile_pic.attached? %>
                <%= image_tag current_user.profile_pic, class: "img-thumbnail rounded-circle", style: "width: 10%" %>
              <% else %>
                <%= image_tag "user-pp.png", class: "img-thumbnail rounded-circle", style: "width: 10%" %>
              <% end %>
              <span class="fw-bold mx-2"><%= current_user.username %></span>
            </div>
            <div>
              <%= form.text_area :caption, rows:8, placeholder: "Write a caption...", class: "form-control border-0", style: "resize:none" %>
            </div>

            <div>
              <%= form.text_field :location, placeholder: "Add location", class: "form-control" %>
            </div>

            <div class="d-flex justify-content-between align-item-center border form-control my-2" data-bs-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
              <a class="text-dark" style="text-decoration:none">
                Advanced Settings
              </a>
              <i class="fa-solid fa-chevron-down"></i>
            </div>

            <div class="collapse" id="collapseExample">
              <div class="card card-body">
                <div class="form-check form-switch">
                  <%= form.check_box :allow_comments, class: "form-check-input", role: "switch", checked: true %>
                  <%= form.label :allow_comments, style: "display: block", class: "form-check-label" %>
                </div>

                <div class="form-check form-switch">
                  <%= form.check_box :show_likes_count, class: "form-check-input", role: "switch", checked: true %>
                  <%= form.label :show_likes_count, style: "display: block", class: "form-check-label" %>
                </div>
              </div>
            </div>
            
          </div>
        </div>
        <div class="modal-footer">
          <%= form.submit "Post", class: "btn btn-primary" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/_liker.html.erb
<div class="d-flex justify-content-between">
  <div class="d-flex">
    <%= image_tag liker.profile_pic.attached? ? liker.profile_pic : 'user-pp.png', class: "img-thumbnail rounded-circle", style: "width: 2.5rem" %>
    <div class="d-flex flex-column mx-3 justify-content-center">
      <small class="fw-bold" style="overflow: hidden;text-overflow: ellipsis;white-space: nowrap;max-width:10rem"><%= link_to liker, class: "a-decoration-none", data: {turbo: 'false'} do %><%= liker.username %><% end %></small>
    </div>
  </div>

  <%= render 'layouts/shared/follow_state', user: liker %>
</div>

app/views/posts/_modal_comment.html.erb
<div id="post<%=comment.post_id%>ModalComment<%=comment.id%>">
  <div class="d-flex justify-content-between">
    <div class="d-flex">
      <%= image_tag comment.user.profile_pic.attached? ? comment.user.profile_pic : 'user-pp.png', class: "img-thumbnail rounded-circle", style: "width: 2.5rem; max-height:2.5rem" %>  
        <div class="d-flex flex-column mx-3 justify-content-center">
          <small class="fw-bold" style="overflow: hidden; text-overflow: ellipsis; white-space: nowrap;max-width:10rem"><%= link_to comment.user, class: "a-decoration-none", data: {turbo: 'false'} do %><%= comment.user.username %><% end %></small>
          <small> <%= comment.body %> </small>
          <small class="text-muted"> <%= time_ago_in_words(comment.created_at) %> </small>
        </div>
    </div>
    <% if comment.user == current_user %>
      <%= button_to comment_path(id: comment.id), method: :delete, style: "background:none; border:none " do %>
        <i class="fa fa-times"></i>
      <% end %>
    <% end %>
  </div>
</div>

app/views/posts/_post.html.erb
<div class="my-3" id="<%= dom_id post %>">

  <div class="card" style="width: 25rem;">
    <div class="card-header bg-white">
      <div class="d-flex justify-content-between">
        <div>
          <%= link_to post.user, class: "a-decoration-none" do %>
            <% if post.user.profile_pic.attached? %>
              <%= image_tag post.user.profile_pic, class: "img-thumbnail rounded-circle", style: "width: 10%" %>
            <% else %>
              <%= image_tag "user-pp.png", class: "img-thumbnail rounded-circle", style: "width: 10%" %>
            <% end %>
          <% end %>
          <%= link_to post.user, class: "a-decoration-none" do %>
            <span class="fw-bold mx-2"><%= post.user.username %></span>
          <% end %>
        </div>

        <div>
          <div class="dropdown">
            <a class="text-dark fs-4" style="text-decoration:none" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              ...
            </a>

            <ul class="dropdown-menu">
              <li><%= button_to 'Delete post', post, method: :delete, class:"dropdown-item" %></li>
            </ul>
          </div>
        </div>

      </div>
    </div>

    <div class="card-body">
      <div id="post<%= post.id %>_images" class="carousel slide" data-bs-ride="true">        
        <div class="carousel-inner">
          <% post.images.each_with_index do |img, i| %>
            <div class="carousel-item <%= i==0 ? 'active' : '' %>" style="height: 25rem">
              <%= image_tag img, class: "d-block w-100", style: "max-height: 100%; object-fit: cover;" %>
            </div>
          <% end %>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#post<%= post.id %>_images" data-bs-slide="prev">
          <span class="carousel-control-prev-icon bg-dark rounded-circle" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#post<%= post.id %>_images" data-bs-slide="next">
          <span class="carousel-control-next-icon bg-dark rounded-circle" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>
        <div class="carousel-indicators" style="position:static">
          <% post.images.each_with_index do |img, i| %>
            <button type="button" data-bs-target="#post<%= post.id %>_images" data-bs-slide-to="<%= i %>" class=" bg-dark <%= i==0 ? 'active' : '' %>" <%= i==0 ? 'aria-current="true"' : '' %> aria-label="Slide <%= i+1 %>"></button>
          <% end %>
        </div>
      </div>
      <%= render "posts/post_actions", post: post %>
      <p class="card-text"><span class="fw-bold"><%= post.user.username %></span> <%= post.caption %></p>

      <%= render "posts/post_comments", post: post %>

      <small class="text-muted"><%= time_ago_in_words(post.created_at) %></small>
    </div>
    <%= form_with url: comments_path, method: :post, data: {controller: "comments", action: "turbo:submit-end->comments#clear"} do |f| %>
      <div class="card-hooter d-flex justify-content-between bg-white">
        <%= f.hidden_field :post_id, value: post.id %>
        <%= f.text_area :comment_body, class: "w-75", placeholder: "Add a comment...", style: "border:none" %>
        <%= f.submit "Post", class: "text-primary fw-bold", style: "background:none;border:none" %>
      </div>
    <% end %>
  </div>

</div>

<script>
  document.getElementById("post<%= post.id %>_images").addEventListener("dblclick", function(){
    document.getElementById("post<%=post.id%>actions-likeBtn").click();
  })
</script>

app/views/posts/_post_actions.html.erb
<%= turbo_frame_tag "post#{post.id}actions" do %>
  <div class="d-flex justify-content-start align-items-center gap-1 mb-3">
    <%= button_to toggle_like_path(post_id: post.id), method: :post, style: "border:none; background:none", id: "post#{post.id}actions-likeBtn" do %>
      <i class="<%= post.likes.find_by(user: current_user) ? "fa-solid color-red" : "fa-regular" %> fa-heart fa-xl"></i>
    <% end %>
    <a href="#" data-bs-toggle="modal" data-bs-target="#post<%= post.id %>_commentsModal" style="text-decoration:none" >
      <i class="fa-regular fa-comment fa-xl fa-flip-horizontal text-dark"></i>
    </a>
  </div>
  <a href="#" data-bs-toggle="modal" data-bs-target="#post<%= post.id %>_likesModal" style="text-decoration:none" class="text-dark">
    <small class="fw-bold my-1"><%= pluralize(post.likes.count, "like") %></small>
  </a>

  <!-- Modal -->
  <div class="modal fade" id="post<%= post.id %>_likesModal" tabindex="-1" aria-labelledby="post<%= post.id %>_likesModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="post<%= post.id %>_likesModalLabel">Post Likes</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <div class="d-flex flex-column gap-3" >
            <% post.likers.each do |liker| %>
              <%= render "posts/liker", liker: liker %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/posts/_post_comments.html.erb
<%= turbo_frame_tag "post#{post.id}comments" do %>
  <% if post.comments.count > 0 %>
    <a href="#" data-bs-toggle="modal" data-bs-target="#post<%= post.id %>_commentsModal" style="text-decoration:none" >
      <small class="text-muted">View all <%= pluralize(post.comments.count, "comments") %></small>
    </a>
  <% end %>
  <% post.comments.last(5).each do |comment| %>
    <p class="card-text m-0"><%= link_to comment.user, class: "a-decoration-none", data: {turbo: 'false'} do %> <span class="fw-bold"><%= comment.user.username %></span><% end %> <%= comment.body %></p>  
  <% end %>

  <!-- Modal -->
  <div class="modal fade" id="post<%= post.id %>_commentsModal" tabindex="-1" aria-labelledby="post<%= post.id %>_commentsModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="post<%= post.id %>_commentsModalLabel">Post Comments</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <div class="d-flex flex-column gap-3" >
            <% post.comments.each do |comment| %>
              <%= render "posts/modal_comment", comment: comment %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Posts</h1>

<div id="posts">
  <% @posts.each do |post| %>
    <%= render post %>
    <p>
      <%= link_to "Show this post", post %>
    </p>
  <% end %>
</div>

<%= link_to "New post", new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>
<div class="d-flex justify-content-center mt-4">
  <%= render @post %>
</div>