config/routes.rb
Rails.application.routes.draw do
  resources :posts
  devise_for :users
  # get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"

  post "toggle_like", to: "likes#toggle_like", as: :toggle_like

  resources :comments, only: [:create, :destroy]

  resources :users, only: [:show, :index]

  post "follow", to: "follows#follow", as: :follow
  delete "unfollow", to: "follows#unfollow", as: :unfollow
  delete "cancel_request", to: "follows#cancel_request", as: :cancel_request

  post "accept_follow", to: "follows#accept_follow", as: :accept_follow
  delete "decline_follow", to: "follows#decline_follow", as: :decline_follow

end

app/views/suggestions/_suggestion.html.erb
<div class="d-flex justify-content-between">
  <div class="d-flex">
    <%= image_tag suggestion.profile_pic.attached? ? suggestion.profile_pic : 'user-pp.png', class: "img-thumbnail rounded-circle border", style: "width: 2.5rem" %>
    <div class="d-flex flex-column mx-2">
      <small class="fw-bold" style="overflow: hidden; text-overflow: ellipsis; white-space: nowrap;max-width:10rem"><%= link_to suggestion, class: "a-decoration-none", data: {turbo: 'false'} do %><%= suggestion.username %><% end %></small>
      <small class="text-muted" style="font-size:.7rem;overflow: hidden; text-overflow: ellipsis; white-space: nowrap;max-width:10rem">Suggested for you by Instagram as He followed you before</small>
    </div>
  </div>

  <% if current_user.waiting_followings.include?(suggestion) %>
    <%= button_to cancel_request_path(user_id: suggestion.id), method: :delete, class: "btn bg-transparent border-0", data: {turbo: 'false'} do %>
      <small class="fw-bold text-secondary">Cancel</small>
    <% end %>
  <% else %>
    <%= button_to follow_path(user_id: suggestion.id), method: :post, class: "btn bg-transparent border-0", data: {turbo: 'false'} do %>
      <small class="fw-bold text-primary">Follow</small>
    <% end %>
    
  <% end %>
</div>

app/views/suggestions/_suggestions_list.html.erb
<div class="" style="width: 20rem">
  <div class="d-flex flex-row justify-content-between">  
    <p class="text-muted fw-bold">Suggestions for you</p>
    <%= link_to root_path, style:"text-decoration:none" do %>
      <small class="fw-bold text-dark">See All</small>
    <% end %>
  </div>

  <div class="d-flex flex-column gap-3 px-2">
    <% suggestions.each do |suggestion| %>
      <%= render 'suggestions/suggestion', suggestion: suggestion %>
    <% end %>
  </div>
</div>