config/routes.rb
Rails.application.routes.draw do
  resources :posts
  devise_for :users
  # get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"

  post "toggle_like", to: "likes#toggle_like", as: :toggle_like

  resources :comments, only: [:create, :destroy]

  resources :users, only: [:show, :index]

  post "follow", to: "follows#follow", as: :follow
  delete "unfollow", to: "follows#unfollow", as: :unfollow
  delete "cancel_request", to: "follows#cancel_request", as: :cancel_request

  post "accept_follow", to: "follows#accept_follow", as: :accept_follow
  delete "decline_follow", to: "follows#decline_follow", as: :decline_follow

end

app/views/layouts/_flash_messages.html.erb
<% if notice && notice.is_a?(Array) %>
  <% notice.each do |n| %>
    <p class="alert alert-success"> <%= n %> </p>
  <% end %>
<% elsif notice && notice.is_a?(String) %>
  <p class="alert alert-success"> <%= notice %> </p>
<% end %>

<% if alert && alert.is_a?(Array) %>
  <% alert.each do |a| %>  
    <p class="alert alert-danger"> <%= a %> </p>
  <% end %>
<% elsif alert && alert.is_a?(String) %>
  <p class="alert alert-danger"> <%= alert %> </p>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary sticky-top bg-white border-bottom" style="border-color: #afafaf">
  <div class="container-fluid w-75">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag 'logo.png', width: "100rem" %>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="d-flex">
      <div class="collapse navbar-collapse me-5" id="navbarSupportedContent">
        <%= form_with(url: users_path, method: :get, data: {turbo_frame: "search_results", controller: "search-results"}, class: "d-flex") do |f| %>

          <div class="dropdown">
            <%= f.text_field :search_query, class: "form-control me-2 border-0", type: "search", placeholder: "Search",
              "aria-label"=>"Search", style: "background: #efefef", "data-bs-toggle"=>"dropdown", "data-bs-toggle"=>"dropdown", "aria-expanded"=>"false",
              data: {action: "input->search-results#search"} %>

            <ul class="dropdown-menu p-4 mt-2" style="width:25rem">
              <%= render 'layouts/search_results', users: [] %>
            </ul>
          </div>

        <% end %>
      </div>

      <div class="navbar-collapse gap-4">
        <%= link_to root_path, class: "text-dark" do %> <i class="fa-solid fa-house fa-xl"></i><% end %>
        <i class="fa-brands fa-facebook-messenger fa-xl"></i>
        <a type="button" class="text-dark" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
          <i class="fa-regular fa-square-plus fa-xl text-dark"></i>
        </a>
        <i class="fa-regular fa-compass fa-xl"></i>

        <div class="dropstart">
          <i class="fa-regular fa-heart fa-xl" data-bs-toggle="dropdown" aria-expanded="false"></i>
          <ul class="dropdown-menu p-4">
            <% current_user.follow_requests.each do |fr| %>
              <li>
                <div class="d-flex justify-content-between">
                  <div class="d-flex">
                    <%= image_tag fr.follower.profile_pic.attached? ? fr.follower.profile_pic : 'user-pp.png', class: "img-thumbnail rounded-circle", style: "width: 2.5rem" %>
                    <div class="d-flex flex-column mx-3 justify-content-center">
                      <small class="fw-bold" style="overflow: hidden;text-overflow: ellipsis;white-space: nowrap;max-width:5rem"> <%= link_to fr.follower, class: "a-decoration-none" do %> <%= fr.follower.username %> <% end %> </small>
                    </div>
                  </div>

                  <div class="d-flex flex-row align-items-center justify-content-between", style="width: 11rem">
                    <%= button_to accept_follow_path(follow_id: fr.id), method: :post, class: "btn btn-primary", style: "text-decoration:none" do %>
                      <small class="fw-bold text-white">Accept</small>
                    <% end %>
                    <%= button_to decline_follow_path(follow_id: fr.id), method: :delete, class: "btn btn-danger", style: "text-decoration:none" do %>
                      <small class="fw-bold text-white">Decline</small>
                    <% end %>
                  </div>
                    
                </div>
              </li>
            <% end %>
          </ul>
        </div>

        <div class="dropdown">
          <a class="" type="button" data-bs-toggle="dropdown" aria-expanded="false">
            <% if current_user && current_user.profile_pic.attached? %>
              <%= image_tag current_user.profile_pic, class: "img-thumbnail rounded-circle", style: "width: 2rem" %>
            <% else %>
              <%= image_tag 'user-pp.png', class: "img-thumbnail rounded-circle", style: "width: 2rem" %>
            <% end %>
          </a>
          <ul class="dropdown-menu">
            <li>
              <%= link_to 'Profile', user_path(current_user), class: "dropdown-item" %>
            </li>
            <li>
              <%= link_to 'Settings', edit_user_registration_path, class: "dropdown-item" %>
            </li>
            <li>
              <%= button_to 'Log out', destroy_user_session_path, class: "dropdown-item", method: :delete%>
            </li>
          </ul>
        </div>

      </div>
    </div>
  </div>
</nav>

<%= render 'posts/form', post: Post.new %>

app/views/layouts/_search_results.html.erb
<%= turbo_frame_tag "search_results" do %>
  <% users.each do |u| %>
    <li class="mt-3">
      <div class="d-flex justify-content-between">
        <div class="d-flex">
          <%= image_tag u.profile_pic.attached? ? u.profile_pic : 'user-pp.png', class: "img-thumbnail rounded-circle", style: "width: 2.5rem" %>
          <div class="d-flex flex-column mx-3 justify-content-center">
            <small class="fw-bold" style="overflow: hidden;text-overflow: ellipsis;white-space: nowrap;max-width:10rem"> <%= link_to u, class: "a-decoration-none", data: {turbo: false} do %> <%= u.username %> <% end %> </small>
          </div>
        </div>                      
      </div>
    </li>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instagram</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if current_user %>
      <%= render 'layouts/navbar' %>
    <% end %>
    <%= yield %>
  </body>
</html>